const config = {
  baseUrl: 'http://127.0.0.1:8000',
  login: 'login',
  logout: 'logout',
  governments: {
    all: 'governorates/all',
    search: 'governorate/search',
    add: 'governorate/add',
    edit: 'governorate/update',
  },
  cities: {
    all: 'city/index',
    search: 'city/search',
    add: 'city/add',
    edit: 'city/update',
    filter: 'city/filter',
  },
  areas: {
    all: 'district/index',
    search: 'district/search',
    add: 'district/add',
    edit: 'district/update',
    filter: 'district/filter',
  },
  campaigns: {
    all: 'campaign/index',
    search: 'campaign/searchByname',
    add: 'campaign/add',
    edit: 'campaign/update',
    filter: 'campaign/filter',
    campaignDetails: 'campaign/show',
    addProjects: 'campaign/project/add',
    deleteProject: 'campaign/project/delete',
    delete: 'campaign/delete',
    stop: 'campaign/stop',
    resume: 'campaign/appeal',
    status: 'campaign/status',
    trash: 'campaign/deleted',
    restore: 'campaign/restore',
  },
  projects: {
    all: 'project/index',
    search: 'project/searchByname',
    add: 'project/add',
    edit: 'project/update',
    filter: 'project/filter',
    projectDetails: 'project/show',
    delete: 'project/delete',
    fundingSources: 'project/fundingsource',
    sectors: 'project/sectors',
    status: 'project/status',
    details: {
      all: 'details/all',
      add: 'projects/details/add',
      delete: 'detail/delete',
      edit: 'project/details/update',
    },
    unattached: 'get/projects',
    addCampaign: 'project/campaign',
    media: {
      upload: 'project/upload',
      deleteVideo: 'videos/delete',
      deleteImage: 'images/delete',
    },
  },
  activities: 'api/activities',
  contact: 'api/contactForms/contact-us/',
};
export default config;
